[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "analise-turma"
version = "1.0.0"
requires-python = ">=3.12"

[tool.setuptools.packages.find]
where = ["."]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
